### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [andreashetland/sublime-text-ox#1]
I would like to use your grammar for Ox but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by andreashetland** [comment]
Dear Paul, I have included the MIT license in the readme file. The package is based on the C/C++ grammar for TextMate. To the best of my knowledge, the MIT license does not violate their [license](https://github.com/textmate/c.tmbundle#license). Thank you for pointing this oversight out -- it's my first publicly available project. I hope you will find it useful. Best, Andreas

**Comment by pchaigno** [comment]
Thanks!

**Comment by pchaigno** [comment]
@andreashetland Your grammar is now used to highlight Ox code on GitHub (files and code snippets in Markdown documents)! (See github/linguist#2071 for more information.)

**Comment by andreashetland** [comment]
Hi Paul, that's great! I am still making the occasional addition to the patterns; will you be including these automatically?

**Comment by pchaigno** [comment]
The maintainers of github/linguist (I'm not myself from GitHub, I only contribute) update all the grammars with each new release (usually every couple weeks).
